# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
github_urls:
  skip_tls_verify: true
builds:
- id: build1
  binary: foo
  env:
  - CGO_ENABLED=0
  main: ./main.go
  goos:
  - darwin
  goarch:
  - amd64
- id: build2
  binary: foo
  env:
  - CGO_ENABLED=0
  main: ./foo/main.go
  goos:
  - linux
  goarch:
  - amd64
dockers:
- image_templates:
  - caarlos0/foo
  binaries:
  - foo
  builds:
  - build2
  dockerfile: Dockerfile.foo
