# This file was generated by GoReleaser. DO NOT EDIT.
class Test < Formula
  desc ""
  homepage ""
  url "https://github.com/caarlos0/test/releases/download/v5.6.0/test_5.6.0_Darwin_x86_64.tar.gz"
  version "5.6.0"
  sha256 "ccedfdc4d07f35ab9957a4400a017e9ca30df6a2b43549f7bedba1c56e137e53"

  def install
    bin.install "moises"
    bin.install "foo"
    bin.install "bar"
  end

  def caveats; <<~EOS
    Test formula, dont use it. It doesnt do anything
  EOS
  end
end
